version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app  # Sync backend code with container
    environment:
      - BACKEND_URL=http://localhost:8000  # Si nécessaire pour ton code backend

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistence des données MongoDB

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000  # Passer l'URL en variable d'environnement pour le frontend
    volumes:
      - ./frontend:/app  # Sync frontend code with container

volumes:
  mongo-data:
